### ISSUE TITLE
Inconsistent predictions between models

### ISSUE THREAD

**Issue by kyrozepto** [Bin-Detective/bindetective-ML-backend#1]
Different predictions between initial model performance and its deployment. My first guess was a potential data type mismatch during image preprocessing in <a href='https://github.com/Bin-Detective/bindetective-ML-backend/blob/main/src/handler.py' target='_blank'>handler.py:</a>
```bash
class WastePredictionServicer:
    def predict(self, image_bytes: bytes):
        try:
            image = Image.open(io.BytesIO(image_bytes)).resize((224, 224))
            image_array = np.expand_dims(np.array(image) / 255.0, axis=0)
```
try changing it to
```bash
image_array = np.expand_dims(np.array(image, dtype=np.uint8), axis=0)
```

**Comment by x1nx3r** [comment]
Your guess is absolutely spot on, sorry for the oversight. I'll fix this up real quick and notify you when it's done. Thank you for the input

**Comment by x1nx3r** [comment]
I've applied the fix and deployed it so it should be online now. From my little testing it looks like it's working fine now but I'll be glad if you're able to test it out from your side.

**Comment by kyrozepto** [comment]
Thanks for the fix. The previous dtype adjustment has slightly improved the predictions in the deployed environment, but the model predictions still show differences with the results tested on Kaggle. 

When [Metal_10.jpg ](https://storage.googleapis.com/kagglesdsdata/datasets/4324996/7432092/realwaste-main/RealWaste/Metal/Metal_10.jpg?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20241126%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20241126T023812Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=8ab72ff5531f418b7e895a57264ba89b8e63944d7707fa0ce5ef3f85fced84aee565131e8247ae7ecdf7763b83c7ceba2956f89a74c27bc171c3a4568b0ed1afb072bca72ac474c2cb688cdc523e3fae7edfc381f75cd66161db987bfc52792b52eebe168acafc5fa250fdc594190f2dfee546b4c2358a6d2ede436acb7e18680b78c9489d535f751237cf538c55038ae1a71a914c00b01958791903ea63e100e7bcb3aa9b60300ca752bd5c365fc02d90ac33bef878037ed3598a41cba61fea176f521f91380db8374dcd7f4d19846c17e4c2ff07ba0120e526cfad377a1943b51c82a28778985069da0edae1154cb8947da47aa74344e706f2eb3a03528ff4)tested, the deployed model returns the following prediction:

```json
{
  "imageUrl": "#####",
  "predicted_class": "logam",
  "waste_type": "anorganik",
  "probabilities": {
    "buah_sayuran": 0.00000935040952754207,
    "daun": 0.00001280352626054082,
    "elektronik": 0.00000842738700157497,
    "kaca": 0.0003416250692680478,
    "kertas": 0.0000979607502813451,
    "logam": 0.5288726091384888,
    "makanan": 0.00001739530125632882,
    "medis": 0.47051578760147095,
    "plastik": 0.00006641953950747848,
    "tekstil": 0.000057631998060969636
  }
}
```
While the same tested model on Kaggle returns the following predictions:
```bash
1/1 [==============================] - 0s 133ms/step
{'predicted_class': 'logam', 'waste_type': 'anorganik', 'probabilities': {'buah_sayuran': 0.00015537232684437186, 'daun': 2.2661552065983415e-05, 'elektronik': 3.881779048242606e-05, 'kaca': 2.870157732104417e-05, 'kertas': 5.2285584388300776e-05, 'logam': 0.9991063475608826, 'makanan': 4.0144528611563146e-05, 'medis': 0.00022748325136490166, 'plastik': 1.5667666275476222e-06, 'tekstil': 0.000326696434058249}}
```

with the similar prediction code,
```bash
def load_image_as_bytes(image_path: str):
    """Load an image from the file system and return it as bytes."""
    with open(image_path, 'rb') as f:
        image_bytes = f.read()
    return image_bytes

def predict_image_details(model, image_path, class_labels, waste_types):
    try:
        image_bytes = load_image_as_bytes(image_path)

        image = Image.open(io.BytesIO(image_bytes)).resize((224, 224))
        image_array = np.expand_dims(np.array(image, dtype=np.uint8), axis=0)

        prediction = model.predict(image_array)
        predicted_index = np.argmax(prediction[0])
        predicted_class = class_labels[predicted_index]
        waste_type = waste_types[predicted_class]

        response = {
            "predicted_class": predicted_class,
            "waste_type": waste_type,
            "probabilities": {
                class_labels[i]: float(prob) for i, prob in enumerate(prediction[0])
            }
        }
        return response
    except Exception as e:
        return {"error": str(e)}

image_path = "/kaggle/input/realwaste/realwaste-main/RealWaste/Metal/Metal_10.jpg"
details = predict_image_details(model, image_path, class_labels, waste_types)
print(details)
```

I would like to make this issue remain open to identify the cause of the prediction differences and improve model accuracy.

**Comment by kyrozepto** [comment]
Thanks for the fix. The previous dtype adjustment has slightly improved the predictions in the deployed environment, but the model predictions still show differences compared to the results tested on Kaggle.

When [Metal_10.jpg](https://storage.googleapis.com/kagglesdsdata/datasets/4324996/7432092/realwaste-main/RealWaste/Metal/Metal_10.jpg?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20241126%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20241126T023812Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=8ab72ff5531f418b7e895a57264ba89b8e63944d7707fa0ce5ef3f85fced84aee565131e8247ae7ecdf7763b83c7ceba2956f89a74c27bc171c3a4568b0ed1afb072bca72ac474c2cb688cdc523e3fae7edfc381f75cd66161db987bfc52792b52eebe168acafc5fa250fdc594190f2dfee546b4c2358a6d2ede436acb7e18680b78c9489d535f751237cf538c55038ae1a71a914c00b01958791903ea63e100e7bcb3aa9b60300ca752bd5c365fc02d90ac33bef878037ed3598a41cba61fea176f521f91380db8374dcd7f4d19846c17e4c2ff07ba0120e526cfad377a1943b51c82a28778985069da0edae1154cb8947da47aa74344e706f2eb3a03528ff4) is tested in the deployed environment, it returns the following prediction:

```json
{
  "imageUrl": "#####",
  "predicted_class": "logam",
  "waste_type": "anorganik",
  "probabilities": {
    "buah_sayuran": 0.00000935040952754207,
    "daun": 0.00001280352626054082,
    "elektronik": 0.00000842738700157497,
    "kaca": 0.0003416250692680478,
    "kertas": 0.0000979607502813451,
    "logam": 0.5288726091384888,
    "makanan": 0.00001739530125632882,
    "medis": 0.47051578760147095,
    "plastik": 0.00006641953950747848,
    "tekstil": 0.000057631998060969636
  }
}
```

While the model being tested on Kaggle, returns the following prediction:

```bash
1/1 [==============================] - 0s 133ms/step
{'predicted_class': 'logam', 'waste_type': 'anorganik', 'probabilities': {'buah_sayuran': 0.00015537232684437186, 'daun': 2.2661552065983415e-05, 'elektronik': 3.881779048242606e-05, 'kaca': 2.870157732104417e-05, 'kertas': 5.2285584388300776e-05, 'logam': 0.9991063475608826, 'makanan': 4.0144528611563146e-05, 'medis': 0.00022748325136490166, 'plastik': 1.5667666275476222e-06, 'tekstil': 0.000326696434058249}}
```
with the similar code,
```bash
def load_image_as_bytes(image_path: str):
    """Load an image from the file system and return it as bytes."""
    with open(image_path, 'rb') as f:
        image_bytes = f.read()
    return image_bytes

def predict_image_details(model, image_path, class_labels, waste_types):
    try:
        image_bytes = load_image_as_bytes(image_path)

        image = Image.open(io.BytesIO(image_bytes)).resize((224, 224))
        image_array = np.expand_dims(np.array(image, dtype=np.uint8), axis=0)

        prediction = model.predict(image_array)
        predicted_index = np.argmax(prediction[0])
        predicted_class = class_labels[predicted_index]
        waste_type = waste_types[predicted_class]

        response = {
            "predicted_class": predicted_class,
            "waste_type": waste_type,
            "probabilities": {
                class_labels[i]: float(prob) for i, prob in enumerate(prediction[0])
            }
        }
        return response
    except Exception as e:
        return {"error": str(e)}

image_path = "/kaggle/input/realwaste/realwaste-main/RealWaste/Metal/Metal_10.jpg"
details = predict_image_details(model, image_path, class_labels, waste_types)
print(details)
```

- The model being tested on Kaggle returns a 99% confidence score, when the one tested in deployed environment showing 53% confidence score.

I would like to make this issue remain open to identify the cause of the prediction differences and improve the model accuracy further.

**Comment by x1nx3r** [comment]
Hey there, I maybe have found the fix for this issue, after disabling the tensorflow's TF_ENABLE_ONEDNN_OPTS flag on my local development environment. It looks like the performance has gotten roughly 1:1 with your training environment. I tested the file [Metal_10.jpg](https://storage.googleapis.com/kagglesdsdata/datasets/4324996/7432092/realwaste-main/RealWaste/Metal/Metal_10.jpg?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20241126%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20241126T023812Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=8ab72ff5531f418b7e895a57264ba89b8e63944d7707fa0ce5ef3f85fced84aee565131e8247ae7ecdf7763b83c7ceba2956f89a74c27bc171c3a4568b0ed1afb072bca72ac474c2cb688cdc523e3fae7edfc381f75cd66161db987bfc52792b52eebe168acafc5fa250fdc594190f2dfee546b4c2358a6d2ede436acb7e18680b78c9489d535f751237cf538c55038ae1a71a914c00b01958791903ea63e100e7bcb3aa9b60300ca752bd5c365fc02d90ac33bef878037ed3598a41cba61fea176f521f91380db8374dcd7f4d19846c17e4c2ff07ba0120e526cfad377a1943b51c82a28778985069da0edae1154cb8947da47aa74344e706f2eb3a03528ff4) it returns these results :
``` json
{
    "predicted_class": "logam",
    "waste_type": "anorganik",
    "probabilities": {
        "buah_sayuran": 0.00015537305444013327,
        "daun": 2.266161209263373e-05,
        "elektronik": 3.881800876115449e-05,
        "kaca": 2.8701682822429575e-05,
        "kertas": 5.228572626947425e-05,
        "logam": 0.999106228351593,
        "makanan": 4.014467776869424e-05,
        "medis": 0.00022748475021217018,
        "plastik": 1.5667709476474556e-06,
        "tekstil": 0.0003266973071731627
    }
}
```
I'll get this one deployed ASAP so you could do further testing. Cheers 🍻

**Comment by x1nx3r** [comment]
Alright, it's now up in the cloud. I look forward to receiving your feedback on the performance

**Comment by x1nx3r** [comment]
After conducting a thorough investigation into the performance disparity, I have identified several contributing factors:
- **Model Fetching During Build Time**
Initially, I configured the app to pull the model at build time rather than runtime to reduce startup time. However, this inadvertently caused the app to retrieve the wrong model. While this oversight was minor, debugging it consumed more time than expected. I regret the error and have implemented measures to prevent similar issues in the future.
- **Impact of the `TF_ENABLE_ONEDNN_OPTS` Flag**
By default, the TensorFlow runtime enables the `TF_ENABLE_ONEDNN_OPTS` flag, which is intended to optimize performance by reducing latency and enhancing execution efficiency. Paradoxically, enabling this flag halved the model's performance instead of improving it. Disabling the flag restored the model's performance to expected levels.
- **TensorFlow Version Compatibility**
Using TensorFlow 2.15 introduced several warnings that were not present in earlier versions. To address this, I rolled back to TensorFlow 2.13, which resolved the warnings without further issues.

All in all, debugging this issue was quite challenging, but I’m happy to report that it’s now fully resolved. With all fixes in place, I hereby declare this issue closed.
