### ISSUE TITLE
Support for .png image type in prediction service

### ISSUE THREAD

**Issue by kyrozepto** [Bin-Detective/bindetective-ML-backend#2]
I realized I forgot to include support for images with extra channels. The current implementation of the [WastePredictionServicer class](https://github.com/Bin-Detective/bindetective-ML-backend/blob/main/src/handler.py) does not explicitly handle .png files, which can lead to issues when processing images with an alpha channel (RGBA format).
```bash
class WastePredictionServicer:
    def predict(self, image_bytes: bytes):
        try:
            # Load image from binary data
            image = Image.open(io.BytesIO(image_bytes)).resize((224, 224))
```
adding alpha channel handling:
```bash
class WastePredictionServicer:
    def predict(self, image_bytes: bytes):
        try:
            # Load image from binary data
            image = Image.open(io.BytesIO(image_bytes))

            if image.mode != 'RGB':
                image = image.convert('RGB')

            image.resize((224,224))
```

**Comment by x1nx3r** [comment]
Very well, I’ve added this fix to support handling PNG images to the codebase in commit 182e20b. Honestly, I prefer not dealing with PNGs in storage since they’re much larger compared to JPGs. But for the sake of compatibility, I’ve included it. Besides, Android’s default format is JPG, so it shouldn’t have much of an impact on our storage.
